WorkDayApplication/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WorkDayApplication.Models;

namespace WorkDayApplication.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: EmployeeController
        public ActionResult EmployeeList()
        {
            Employee emp = new Employee();
            return View(emp.GetEmployeeList());
        }
 
        public ActionResult EmployeeStatus(int id,bool status)
        {
            Employee emp = new Employee();
            emp.ChangeStatus(id, status);
            return RedirectToAction("EmployeeList");
        }

        //// GET: EmployeeController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: EmployeeController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: EmployeeController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: EmployeeController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: EmployeeController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: EmployeeController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: EmployeeController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

WorkDayApplication/Controllers/LeaveController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WorkDayApplication.Models;

namespace WorkDayApplication.Controllers
{
    public class LeaveController : Controller
    {
        public ActionResult LeaveAccount()
        {
            LeaveAccount leaveacc = new LeaveAccount();
            return View(leaveacc.GetLeaveAccount("232403"));
        }

        // GET: LeaveController/Details/5
        public ActionResult ApplyLeave(int Leaveid)
        {
            Leave leave = new Leave();
            leave.ApplyLeave(Leaveid);
            return RedirectToAction("LeaveAccount");
        }
        public ActionResult CancelLeave(int Leaveid)
        {
            Leave leave = new Leave();
            leave.CancelLeave(Leaveid);
            return RedirectToAction("LeaveAccount");
        }
        public ActionResult ApproveLeave(int Leaveid)
        {
            Leave leave = new Leave();
            leave.ApproveLeave(Leaveid);
            return RedirectToAction("LeaveAccount");
        }

        //// GET: LeaveController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: LeaveController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: LeaveController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: LeaveController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: LeaveController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: LeaveController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

WorkDayApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkDayApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkDayApplication.styles.css" asp-append-version="true" />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkDayApplication</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="wrapper">

        <nav class="side-menu" id="sidebar">
            <ul class="side-menu-list">
                <li class="pink-red opened">
                    <span>
                        <i class="font-icon font-icon-dashboard"></i>

                        <a class="lbl" href="@Url.Action("EmployeeList", "Employee")">Employee</a>
                    </span>
                </li>
                <li class="pink-red opened">
                    <span>
                        <i class="font-icon font-icon-dashboard"></i>

                        <a class="lbl" href="@Url.Action("DashBoard", "DashBoard")">Attendance</a>
                    </span>
                </li>
                <li class="pink-red opened">
                    <span>
                        <i class="font-icon font-icon-dashboard"></i>

                        <a class="lbl" href="@Url.Action("DashBoard", "DashBoard")">Team Attendance</a>
                    </span>
                </li>
                <li class="purple">
                    <span>
                        <i class="glyphicon glyphicon-user"></i>
                        <a class="lbl" href="@Url.Action("LeaveAccount", "Leave", new { x = "true" })">Leave </a>
                    </span>
                </li>
                <li class="purple">
                    <span>
                        <i class="glyphicon glyphicon-user"></i>
                        <a class="lbl" href="@Url.Action("Profile", "Home", new { x = "true" })">Team Leave </a>
                    </span>
                </li>
                <li class="purple">
                    <span>
                        <i class="glyphicon glyphicon-user"></i>
                        <a class="lbl" href="@Url.Action("Profile", "Home", new { x = "true" })">Holiday List </a>
                    </span>
                </li>
             </ul>
         </nav>
        <div class="page-content">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Team : <a asp-area="" asp-controller="Team" asp-action="Info">232410</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>

</style>